name: 'Docs Updates'
description: 'Detecting app changes that may require docs updates'
inputs:
  config: 
    description: 'location of config file'
    required: true
    default: 'docs-config.yml'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
